version: '3'

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASS=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - /home/shakik/Documents/git-repos/data-engineering-course/Module-1/Docker/ny_taxi_db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80